export const CREATE_POST_REQUEST="CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS="CREATE_POST_SUCCESS"
export const CREATE_POST_FAILED="CREATE_POST_FAILED"


export const GET_POST_REQUEST="GET_POST_REQUEST"
export const GET_POST_SUCCESS="GET_POST_SUCCESS"
export const GET_POST_FAILED="GET_POST_FAILED"



export const PATCH_POST_REQUEST="PATCH_POST_REQUEST"
export const PATCH_POST_SUCCESS="PATCH_POST_SUCCESS"
export const PATCH_POST_FAILED="PATCH_POST_FAILED"



export const DELETE_POST_REQUEST="DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS="DELETE_POST_SUCCESS"
export const DELETE_POST_FAILED="DELETE_POST_FAILED"